<?php

return [
    'ru' => [
        'from' => 'Откуда',
        'to' => 'Что вывозим',
        'settings' => 'Когда',
        'confirm' => 'Подтверждение',
        'taxi_order' => 'Готово',
        'next' => 'Далее',
        'prev' => 'Назад',
        'reject' => 'Отменить заказ',
        'createNewOrder' => 'Создать новый заказ',
        'sms_code' => 'Код из SMS',
        'address' => 'Адрес',
        'street' => 'Улица',
        'findMe' => 'Определить моё местоположение',
        'house' => 'Дом',
        'housing' => 'Корп./стр.',
        'porch' => 'Подъезд',
        'comment' => 'Уточнение для водителя',
        'directionTo' => 'Куда',
        'orderTimeNow' => 'В ближайшее время',
        'orderTimeLater' => 'В определенное время',
        'time' => 'Выберите время',
        'tariffs' => 'Тариф',
        'userName' => 'Ваше имя',
        'userPhone' => 'Телефон',
        'wishes' => 'Доп. опции',
        'createOrder' => 'Далее',
        'calcCostTitle' => 'Примерная сумма',
        'calcCostDist' => 'км',
        'calcCostTime' => 'мин',
        'calcCostCurrency' => '₽',
        'rejectError' => 'Не удалось отменить заказ',
        'rejectConfirm' => 'Вы уверены, что хотите отменить заказ?',
        'autoCompleteNoResultsText' => 'Нет результатов',
        'orderCostTitle' => 'Стоимость заказа',
        'orderDriver' => 'Водитель',
        'orderCar' => 'Автомобиль',
        'orderCarTime' => 'Подъедет через',
        'orderCreated' => 'Информация по заказу №',
        'orderStatus' => 'Статус заказа',
        'orderPrice' => 'Стоимость',
        'new_order' => 'Новый заказ',
    ],
    'en' => [

    ]
];